import { zodResolver } from '@hookform/resolvers/zod'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { createApplicant } from '../../api/services/applicantService.js'
import { useUiStore } from '../../store/uiStore.js'

const schema = z.object({ full_name:z.string().min(2), email:z.string().email(), phone:z.string().min(8), specialization:z.string().min(2), research_statement:z.string().min(100) })
export default function ApplyPage(){const [step,setStep]=useState(0); const [done,setDone]=useState(null); const addToast=useUiStore((s)=>s.addToast); const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(schema),defaultValues:{research_statement:''}}); const submit=async(v)=>{const res=await createApplicant({personal:{full_name:v.full_name,email:v.email,phone:v.phone},academic:{specialization:v.specialization},research_statement:v.research_statement,batch_id:'batch_2024_A'}); setDone(res.data.temp_id); addToast({type:'success',title:'Application submitted'})}; if(done)return <div className="card mx-auto max-w-2xl p-10 text-center"><h1 className="text-3xl font-semibold">Application Submitted</h1><p className="mt-6 rounded-3xl bg-rose-50 p-6 text-3xl font-semibold text-rose-500">{done}</p><p className="mt-4 text-muted">Check your email for the test link.</p></div>; return <form onSubmit={handleSubmit(submit)} className="card mx-auto max-w-3xl p-10"><div className="mb-8 h-2 rounded-full bg-stone-100"><div className="h-2 rounded-full bg-rose-500" style={{width:`${((step+1)/5)*100}%`}}/></div>{step===0&&<div><h1 className="text-4xl font-semibold">Post-Doctoral Fellowship</h1><p className="mt-3 text-muted">A guided application for D.Y. Patil College, Pune.</p></div>}{step===1&&<div className="grid gap-4"><input className="input" placeholder="Full name" {...register('full_name')}/><input className="input" placeholder="Email" {...register('email')}/><input className="input" placeholder="Phone" {...register('phone')}/></div>}{step===2&&<input className="input w-full" placeholder="Specialization" {...register('specialization')}/>} {step===3&&<textarea className="textarea h-48 w-full" placeholder="Research statement, minimum 100 characters" {...register('research_statement')}/>} {step===4&&<div><h2 className="text-2xl font-semibold">Review and submit</h2><p className="text-muted">You can edit details later during onboarding.</p></div>}<p className="mt-3 text-sm text-red-500">{Object.values(errors)[0]?.message}</p><div className="mt-8 flex justify-between"><button type="button" className="rounded-2xl bg-stone-100 px-4 py-3" disabled={step===0} onClick={()=>setStep((s)=>s-1)}>Back</button>{step<4?<button type="button" className="btn-primary" onClick={()=>setStep((s)=>s+1)}>Continue</button>:<button className="btn-primary" disabled={isSubmitting}>{isSubmitting?'Submitting...':'Submit Application'}</button>}</div></form>}
